### PR TITLE
Fix for Deadlock

### LINKED ISSUE #236: Worker deadlocks after receiving balance update
After merge of #228, noting down @arrudagates findings:

> The whole initialization process works fine, the mirrors initialize and the thread starts, the receiver in the enclave works, it reaches that point, but the actual problem is in the sender, or at least in the send function for the balance here: https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/gabriel-dbthread/enclave/src/polkadex_balance_storage/balance_storage.rs#L37-L43
> 
> Up to line 39 everything works fine, it loads the sender as it should but then the send() hangs, it never goes past it and it also doesnt return anything, so thats precisely where its hanging, I'll have to come back to that tomorrow but if you find something out send it here that I'll read in the morning.

### PR DESCRIPTION
**Pull request by arrudagates**
Fixed deadlock in integration testing, which was found to be caused by the receiver being stored and then retrieved, closes #236

### CODE REVIEW

**Review by simonsso — APPROVED** [review]
Looks good, run tests and merge when done

**Comment by arrudagates** [comment]
I already ran unit and integration tests, it's ready for merge.

File: enclave/src/channel_storage.rs [hunk 1]
```diff
@@ -27,20 +27,22 @@ use std::sync::{
 };
 
 lazy_static! {
-    static ref GLOBAL_CHANNEL_STORAGE: Arc<SgxMutex<ChannelStorage>> =
-        Arc::new(SgxMutex::new(ChannelStorage::default()));
+    static ref GLOBAL_CHANNEL_STORAGE: Arc<SgxMutex<Option<ChannelStorage>>> =
+        Arc::new(SgxMutex::new(None));
```
Comment (haerdib) [inline enclave/src/channel_storage.rs:31]: Is the Mutex still necessary? Sender can be cloned with every call, so a lock is actually unnecassary, or am I overlooking something?

File: enclave/src/channel_storage.rs [hunk 2]
```diff
@@ -51,14 +53,16 @@ pub enum ChannelType {
 
 pub fn load_sender() -> Result<Sender<ChannelType>, ChannelStorageError> {
```
Comment (haerdib) [inline enclave/src/channel_storage.rs:54]: I know it's a hassle, but could you write unit tests for this function? I.e. what happens when you load three senders, does it still work or will there be a deadlock? Does the created receiver receive calls from all senders?

Or is it not possible to write unit tests for this?

File: enclave/src/channel_storage.rs (hunk 1 above)
Comment (haerdib) [reply enclave/src/channel_storage.rs:31]: Sorry for being picky about this, but locking takes time, so if we don't need it, we should'nt use it.

Comment (arrudagates) [reply enclave/src/channel_storage.rs:31]: `Sender<ChannelType>` cannot be shared between threads safely, so the mutex is still necessary there

Comment (haerdib) [reply enclave/src/channel_storage.rs:31]: Why not? According to: https://doc.rust-lang.org/std/sync/mpsc/struct.Sender.html

>  `pub struct Sender<T> { /* fields omitted */ }`
> 
> The sending-half of Rust’s asynchronous channel type. This half can only be owned by one thread, but it can be cloned to send to other threads.

Comment (arrudagates) [reply enclave/src/channel_storage.rs:31]: I might be doing something wrong here, but I'm trying to remove the mutex and lazy_static won't let me use Sender
```
29 | / lazy_static! {
30 | |     static ref GLOBAL_CHANNEL_STORAGE: Arc<Option<ChannelStorage>> = Arc::new(None);
31 | | }
   | |_^ `std::sync::mpsc::Sender<ChannelType>` cannot be shared between threads safely
   | 
  ::: /root/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/core_lazy.rs:12:20
   |
12 |   pub struct Lazy<T: Sync>(Once<T>);
   |                      ---- required by this bound in `lazy_static::lazy::Lazy`
```

File: enclave/src/channel_storage.rs (hunk 2 above)
Comment (arrudagates) [reply enclave/src/channel_storage.rs:54]: We do have a problem with tests here, they conflict with the already running Receiver and `substratee-worker test --unit` never finishes running, after running the tests it gets stuck in the receiver loop because it's sender was replaced by the one in the test.

File: enclave/src/channel_storage.rs (hunk 1 above)
Comment (haerdib) [reply enclave/src/channel_storage.rs:31]: Check out: https://stackoverflow.com/questions/40384274/rust-mpscsender-cannot-be-shared-between-threads
respective:
https://teaclave.apache.org/api-docs/crates-enclave/sgx_tstd/sync/mpsc/struct.SyncSender.html

File: enclave/src/channel_storage.rs (hunk 2 above)
Comment (haerdib) [reply enclave/src/channel_storage.rs:54]: `load_sender` should not replace anything, should it?

Comment (arrudagates) [reply enclave/src/channel_storage.rs:54]: In order to test load_sender i also need a receiver to check the message being sent is also being received, and for that i need to create a new channel, leaving the DB Thread receiver without a sender.

Comment (haerdib) [reply enclave/src/channel_storage.rs:54]: I see, then a follow up question: Why are you initializing the DBThread for testing purposes here?
https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/240/files#diff-8bf3b6ae639112751d4db557e3fb729745967cc35382ee32c386488580ffb6c3R36

Comment (arrudagates) [reply enclave/src/channel_storage.rs:54]: Because otherwise the tests that use balance will fail because changes in the balance storage trigger a send to the receiver.

File: enclave/src/channel_storage.rs (hunk 1 above)
Comment (arrudagates) [reply enclave/src/channel_storage.rs:31]: Oh, but then without a Mutex we lose mutability.

Comment (haerdib) [reply enclave/src/channel_storage.rs:31]: Not sure if I can follow this comment.

Comment (arrudagates) [reply enclave/src/channel_storage.rs:31]: https://github.com/Polkadex-Substrate/polkadexTEE-worker/issues/247

File: enclave/src/channel_storage.rs (hunk 2 above)
Comment (arrudagates) [reply enclave/src/channel_storage.rs:54]: https://github.com/Polkadex-Substrate/polkadexTEE-worker/issues/246

**Review by haerdib — APPROVED** [review]
Approving with creation of issues
#246
#247
