### PR TITLE
Clean up and fix account and nonce registry error

### LINKED ISSUE #270: cancel order throwing invalid nonce error
When issueing a cancel order command the following error is thrown:
```
[Error] RPC call failed: SGX_ERROR_UNEXPECTED
[Error] RPC call failed: Authorization error: NonceInvalid
```

### PR DESCRIPTION
**Pull request by haerdib**
- summarizes accout and nonce registry erros to one enum
- fixes rpc error return values to not be always "nonce uninitialized"
- fixes outdated python script cancel-order request
- client now prints success message if cancel_order does not return an error

Output now looks like the following:

```zsh
./substratee-client -p 9994 -P 2094 trusted cancel_order --accountid=//Alice --orderid=oijef03jaf --marketbase=btc --marketquote=usd --mrenclave=9DEggF3cbcuumAjsanchCnsbVjTURqkmUP1PekSWuv7x --direct
[Error] RPC call failed: Authorization error: AccountNotRegistered

./substratee-client -p 9994 -P 2094 register-account //Alice
[+] Transaction got finalized.. Hash: 0x3b5350dc1af8d821e28c4a8d30055985932d3b7daceab273e1631f2878d4856e

 ./substratee-client -p 9994 -P 2094 trusted cancel_order --accountid=//Alice --orderid=oijef03jaf --marketbase=btc --marketquote=usd --mrenclave=9DEggF3cbcuumAjsanchCnsbVjTURqkmUP1PekSWuv7x --direct
[Error] RPC call failed: OpenfinexWebSocketError("\"Failed to send request\"")
```

(interpretation: cancel_order gets through until openfinex client, hence fixing issue #270)

### CODE REVIEW

**Review by arrudagates — APPROVED** [review]
Looks good and very clean.

File: enclave/src/accounts_nonce_storage/error.rs [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+// GNU General Public License for more details.
+
+// You should have received a copy of the GNU General Public License
+// along with this program. If not, see <https://www.gnu.org/licenses/>.
+
+use derive_more::{Display, From};
+use std::result::Result as StdResult;
+
+pub type Result<T> = StdResult<T, Error>;
```
Comment (zktony) [inline enclave/src/accounts_nonce_storage/error.rs:22]: 🙌

**Review by zktony — APPROVED** [review]

**Comment by zktony** [comment]
LGTM
