### PR TITLE
WIP: OpenFinex API implementation

### LINKED ISSUE #5: implement OpenFinex API client
A minimal functionality includes:

* authentication
* `mng_create_order`
* `mng_cancel_order`
* listen to `mng_trade` events and trigger the verification and settlement of matches
* listen to `order` events and update the enclave's orderbook mirror (because orders may only be partly executed by a trade / match)

Remarks:
* Listening to events should happen in its own thread, spawned at worker startup. 
* create and cancel order should be performed with minimal latency

### Authentication

The management websocket authenticate use standard JWT - RS256

```bash
JWT=$(barong-jwt --uid IDBD12DEB15B)
wscat --connect 'ws://localhost:8080/api/v2/finex/ws' -H "Authorization: Bearer ${JWT}"
```

Example of JWT:
```
eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicGVhdGlvIiwiYmFyb25nIl0sImVtYWlsIjoiYWRtaW5AYmFyb25nLmlvIiwiZXhwIjoxNjE3OTU2MjU3LCJpYXQiOjE2MTc5NTI2NTcsImlzcyI6ImJhcm9uZyIsImp0aSI6IjE2MTc5NTI2NTciLCJsZXZlbCI6MywicmVmZXJyYWxfaWQiOm51bGwsInJvbGUiOiJhZG1pbiIsInN0YXRlIjoiYWN0aXZlIiwic3ViIjoic2Vzc2lvbiIsInVpZCI6IlU0ODcyMDU4NjMifQ.ROjIs7OhcsX86ZxxVy5vnBCNheEtOENpI9g7eN4BgbGlz5U3XLg7D9cILw8FEsmfzTf5pSzMRrx59_rD9sI4abim7Nn7eJ8gay7E-vQdFfeu6720ZQkbM3w5hIpq2x6pubzUu88ZCVZA2mLEw2XuQFVtDBCEBT5yWCPIOFSsuVN6wSuANvR2ZpJytJHvzSpeGv_9BxZC0ZtAR4PaP2f_iyX1Zw-71QxB4-BxdZeCUp17ic82DQ7TQU_GgYoQNTQFVBHc_oouj_3XB_B1PIYvbSAoPkS1JalqrwJRIw0nFQfTe09OazACyjGyQpsQqsVBN6WlEjYViV30cGquDRATYg
```

Resources:

- Analyse and generate JWT: www.jwt.io
- Tool to generate JWT for testing: https://github.com/openware/barong-jwt

### Create orders

**Method**: `mng_create_order`

**Arguments**:

| №    | Name            | Data type | Description                                                  |
| ---- | --------------- | --------- | ------------------------------------------------------------ |
| 1    | uid or nickname | string    | User UID or nickname to identify the user                    |
| 2    | market_id       | string    | Market identifier for order ex: "btcusd"                     |
| 3    | market_type     | string    | Market type ex: "trusted"                                    |
| 3    | order_type      | string    | - market: "m"<br />- limit: "l"<br />- Post only (Must not fill at all or is canceled): "p"<br />- Fill or kill (Must fully match at a given price or is canceled): "f" |
| 4    | side            | string    | Used to specify order side, "buy" or "sell"                  |
| 5    | quantity        | string    | An amount that placed within the order                       |
| 6    | price           | string    | Main (limit) price of the order (optional)                   |

**Example**:

```json
[1,42,"mng_create_order",["14dQ6XGcrk4njhYB7ihcjHyyKbFKUVCXt5vffTV9yAWcgrbu", "btcusd", "trusted", "l", "buy", "0.250000", "9120.00"]]
```

**Response**:

```json
[2,42,"mng_create_order",["1245-2345-6798-123123"]]
```

**Error example**:

```json
[2,42,"error",["Message describing the error"]]
```

### Cancel orders

**Method**: `mng_cancel_order_bulk`

**Arguments**:

| №    | Name                | Data type | Description                               |
| ---- | ------------------- | --------- | ----------------------------------------- |
| 1    | uid or nickname     | string    | User UID or nickname to identify the user |
| 2    | market_id           | string    | Market identifier for order ex: "btcusd"  |
| 3    | orders IDs or UUIDs | string    | List of order IDs or UUIDs to cancel      |

**Example**:

```json
[1,42,"mng_cancel_order",["btcusd", ["1245-2345-6798-123123", "1245-2345-6798-123124"]]]
```

#### Subscription to events

*TODO*

#### Order update events
| Argument          |	Description                 |
|-------------------|-----------------------------|
|Market ID          |	Market unique identifier    |
|ID	                |  Unique order ID            |
|UUID	              |  Unique order uuid          |
|Side	              |  "buy" or "sell"            |
|Kind	              |  "bid" or "ask"             |
|State	            |  Current state of the order |
|Type	              |  Order type                 |
|Price	            |  Order price                |
|Average Price	    |  Average execution price    |
|Volume	Current     |  order volume               |
|Origin Volume	    |  Origin volume              |
|Executed Volume    |  Executed volume            |
|Trades Count	Order |  trades count               |
|Timestamp	        |  Order creation timestamp   |

```json
[4,"order",["btcusd", 2, "7acbbc84-939d-11ea-a827-1831bf9834b0", "buy", "bid", "done", "limit", "1", "1", "0", "1", "1", 1, 1589211516]]
```
#### Trades events

| Argument          |	Description                 |
|-------------------|-----------------------------|
|Market ID          |	Market unique identifier    |
|ID	                | Unique trade ID             |
|Price              | Trade execution price       |
|Amount             | Trade execution amount      |
|Funds	            | Trade funds, amount * price |
|Maker OrderID      | Maker's trade order ID      |
|Maker OrderUUID	  | Maker's trade order UUID    |
|Taker OrderID      | Taker's trade order ID      |
|Taker OrderUUID	  | Taker's trade order UUID    |
|Maker Side 	            | Maker order side |
|Timestamp          | Trade timestamp             |

```json
[4,"mng_trade",["btcusd", 1, "1", "1", "1", 2, "55d78eee-939e-11ea-945f-1831bf9834b0", 3, "55d78eee-939e-11ea-945f-1831bf9834as", "buy", 1589211884]]
```

## Debug helpers

The following functions are not strictly needed but it may help debugging if we let OpenFinex know about deposit and withdrawal events:

### Deposit funds

**Method**: `mng_deposit`

**Arguments**:

| №    | Name            | Data type | Description                               |
| ---- | --------------- | --------- | ----------------------------------------- |
| 1    | uid or nickname | string    | User UID or nickname to identify the user |
| 2    | currency_id     | string    | Currency identifier of the deposit        |
| 3    | amount          | number    | Amount to deposit                         |
| 3    | tx_id           | string    | Transaction ID (optional)                 |

**Example**:

```json
[1,42,"mng_deposit",["14dQ6XGcrk4njhYB7ihcjHyyKbFKUVCXt5vffTV9yAWcgrbu", "usd", "1500.000000000000", "0x1234657890123456789"]
```

**Response**:

```json
[2,42,"mng_deposit",[124]]
```

**Error example**:

```json
[2,42,"error",["Message describing the error"]]
```

### Withdraw funds

**Method**: `mng_withdraw`

**Arguments**:

| №    | Name            | Data type | Description                               |
| ---- | --------------- | --------- | ----------------------------------------- |
| 1    | uid or nickname | string    | User UID or nickname to identify the user |
| 2    | currency_id     | string    | Currency identifier of the deposit        |
| 3    | amount          | number    | Amount to withdraw                        |
| 3    | tx_id           | string    | Transaction ID (optional)                 |

**Example**:

```json
[1,43,"mng_withdraw",["14dQ6XGcrk4njhYB7ihcjHyyKbFKUVCXt5vffTV9yAWcgrbu", "usd", "1500", "0x1234657890123456789"]
```

**Response**:

```json
[2,43,"mng_withdraw",[124]]
```

**Error example**:

```json
[2,43,"error",["Message describing the error"]]
```

### LINKED ISSUE #79: Worker crashes upon restart due to broken linked list
The worker crashed upon restart due to `Linkedlist is broken` in function [verify_pdex_account_read_proofs(..)](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/polkadex.rs#L58-L61).

This happens in the following scenario:
1) start node
2) start worker
3) register main account //Alice with `bin/substratee-client register-account //Alice` (currently only available on branch  [ocex-client-calls](https://github.com/Polkadex-Substrate/polkadexTEE-worker/tree/ocex-client-calls))
4) restart worker

This crash is caused due to `account.account.prev != last_account`. 
@Gauthamastro @ksr30 before I look into it, do you perhaps have any input on what goes wrong there?

### PR DESCRIPTION
**Pull request by murerfel**
This PR is to get our current state of the OpenFinex API implementation into develop. Especially the changes in the Polkadex Gateway are relevant for further development when it comes to the callbacks of `create_order`, `settle_trade`, etc.

It is still WIP, but unit tests should be passing.

Fixes #5

### CODE REVIEW

**Comment by haerdib** [comment]
I think it would make sense to merge this PR soon and open issues for all the work that is left, respective changes that are necessary. We can then work on different branches again, making it clearly arranged and easier to split the work load.

File: enclave/src/cert.rs [hunk 1]
```diff
@@ -376,11 +376,11 @@ fn verify_attn_report(report_raw: &[u8], pub_k: Vec<u8>) -> Result<(), sgx_statu
                     if rt != sgx_status_t::SGX_SUCCESS {
                         warn!("ocall_get_update_info unsuccessful. rt={:?}", rt);
                         // Borrow of packed field is unsafe in future Rust releases
-                        unsafe {
+                        /* unsafe {
```
Comment (haerdib) [inline enclave/src/cert.rs:379]: This was commented to remove compiler warnings

File: enclave/src/openfinex/client_utils.rs [hunk 2]
```diff
@@ -0,0 +1,221 @@
...
+/// Masks data to send to a server and writes
+pub fn mask_data(mask: [u8; 4], data: &[u8]) -> Vec<u8> {
+	let mut out = Vec::with_capacity(data.len());
+	let zip_iter = data.iter().zip(mask.iter().cycle());
+	for (&buf_item, &key_item) in zip_iter {
+		out.push(buf_item ^ key_item);
+	}
+	out
+}
+
```
Comment (haerdib) [inline enclave/src/openfinex/client_utils.rs:192]: No unit tests for this client, because it is temporary anyway and will be exchanged with the rustls client as soon as openfinex supports tls.

File: enclave/src/openfinex/jwt.rs [hunk 3]
```diff
@@ -0,0 +1,54 @@
+// more info: https://github.com/mesalock-linux/jsonwebtoken-sgx
+
```
Comment (haerdib) [inline enclave/src/openfinex/jwt.rs:2]: See issue: https://github.com/Polkadex-Substrate/polkadexTEE-worker/issues/97

File: enclave/src/openfinex/openfinex_api.rs [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+pub trait OpenFinexApi {
+    fn create_order(&self, order: Order, request_id: RequestId) -> OpenFinexApiResult<()>;
+
+    fn cancel_order(
+        &self,
+        cancel_order: CancelOrder,
+        request_id: RequestId,
+    ) -> OpenFinexApiResult<()>;
+
+    fn withdraw_funds(&self, request_id: RequestId) -> OpenFinexApiResult<()>;
```
Comment (haerdib) [inline enclave/src/openfinex/openfinex_api.rs:59]: Not yet implemented. Will be done for mainnet (see #98)

File: enclave/src/openfinex/openfinex_api.rs [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+
+    fn deposit_funds(&self, request_id: RequestId) -> OpenFinexApiResult<()>;
```
Comment (haerdib) [inline enclave/src/openfinex/openfinex_api.rs:61]: Not yet implemented. Will be done for mainnet (see #99)

File: enclave/src/openfinex/openfinex_client.rs [hunk 6]
```diff
@@ -0,0 +1,382 @@
...
+
+        // If we're ready but there's no data: EOF.
+        if rc.unwrap() == 0 {
+            error!("EOF");
+            //self.closing = true;
+            //self.clean_closure = true;
+            return Ok(0);
+        }
+
+        if buffer[0] == 72 {
```
Comment (haerdib) [inline enclave/src/openfinex/openfinex_client.rs:158]: This checks for an "H" within the response (for HTTP). A websocket response will always start with 0000 or 1000, never with 72 = 1001000.

Quite ugly but solid solution. Only necessary for temporary self programmed client. Will not be necessary for tls.

File: enclave/src/openfinex/openfinex_client.rs [hunk 7]
```diff
@@ -0,0 +1,382 @@
...
+            // parse http response
+            error!(
```
Comment (haerdib) [inline enclave/src/openfinex/openfinex_client.rs]: temporary debugging solution.. will be changed to debug.

File: enclave/src/openfinex/openfinex_client.rs [hunk 8]
```diff
@@ -0,0 +1,382 @@
...
+            if let Some(message) = client_utils::read_tcp_buffer(buffer.to_vec()) {
+                match message.opcode {
+                    Opcode::PingOp => {
+                        self.send_pong();
+                    }
+                    Opcode::TextOp => {
+                        debug!("received plaintext : {:?}", message.payload);
+                        self.response_handler.handle_text_op(message.payload);
+                    }
+                    _ => error!("received unexpected op: {:?}", message.opcode),
```
Comment (haerdib) [inline enclave/src/openfinex/openfinex_client.rs:177]: We only accept text message (UFT8 encoded) or Pings from the server.. all other websocket calls will be ingored.

File: enclave/src/polkadex.rs [hunk 9]
```diff
@@ -48,7 +53,7 @@ pub fn verify_pdex_account_read_proofs(
                     return Err(sgx_status_t::SGX_ERROR_UNEXPECTED);
                 }
                 if account.account.next.is_some() {
-                    last_account = account.account.next.clone().unwrap();
+                    last_account = account.account.current.clone();
```
Comment (haerdib) [inline enclave/src/polkadex.rs:56]: Fixes #79

File: enclave/src/polkadex.rs [hunk 10]
```diff
@@ -174,62 +180,83 @@ impl PolkadexAccountsStorage {
...
 
-pub fn load_proxy_registry() -> Result<&'static SgxMutex<PolkadexAccountsStorage>, GatewayError> {
+pub fn load_proxy_registry(
+) -> Result<&'static SgxMutex<PolkadexAccountsStorage>, AccountRegistryError> {
     let ptr =
         GLOBAL_ACCOUNTS_STORAGE.load(Ordering::SeqCst) as *mut SgxMutex<PolkadexAccountsStorage>;
     if ptr.is_null() {
-        return Err(GatewayError::UnableToLoadPointer);
+        error!("Null pointer to polkadex account registry");
+        return Err(AccountRegistryError::CouldNotLoadRegistry);
```
Comment (haerdib) [inline enclave/src/polkadex.rs:259]: added some error! messages for easier error location during testing openfinex calls

File: enclave/src/polkadex_balance_storage.rs [hunk 11]
```diff
@@ -118,15 +115,16 @@ impl PolkadexBalanceStorage {
...
+            .get_mut(&PolkadexBalanceKey::from(token, acc.clone()).encode())
         {
             Some(balance) => {
                 balance.free = balance.free.saturating_add(amt);
                 Ok(())
             }
             None => {
-                error!("Account Id or Asset Id not available [here]");
-                return Err(GatewayError::AccountIdOrAssetIdNotFound);
+                debug!("No entry available for given token- and AccountId, creating new.");
```
Comment (haerdib) [inline enclave/src/polkadex_balance_storage.rs:125]: No error but entry creation. See issue #93

File: enclave/src/polkadex_cache/cache_api.rs [hunk 12]
```diff
@@ -0,0 +1,37 @@
...
+
+// This program is distributed in the hope that it will be useful,
+// but WITHOUT ANY WARRANTY; without even the implied warranty of
+// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
+// GNU General Public License for more details.
+
+// You should have received a copy of the GNU General Public License
+// along with this program. If not, see <https://www.gnu.org/licenses/>.
+
+
```
Comment (haerdib) [inline enclave/src/polkadex_cache/cache_api.rs:19]: The following caches I've implemented to replace the previous order cache implementations due to the following reasons:
- cleaner interface
- easier unit testing
- better general overview

but the general logic is the same as Guatham previously implemented it.

File: enclave/src/polkadex_gateway.rs [hunk 13]
```diff
@@ -190,24 +265,56 @@ fn send_cancel_request_to_openfinex(order_uuid: &OrderUUID) -> Result<(), Gatewa
...
+    cache.insert_order(cancel_order.order_id);
+
+    Ok(())
+}
+
+// /// process_cancel_order does the following
+// /// 1. Checks the orderUUID with cancel request cache
+// /// 2. Remove order from Orderbook Mirror
+// /// 3. Mutate the balances
+pub fn process_cancel_order(order_uuid: OrderUUID) -> Result<(), GatewayError> {
```
Comment (haerdib) [inline enclave/src/polkadex_gateway.rs:279]: @Gauthamastro @ksr30 could you take a look at this function and tell us which of the code is necessary? The one comment below or just the uncommented part?

File: enclave/src/polkadex_gateway.rs [hunk 14]
```diff
@@ -381,78 +429,83 @@ pub fn authenticate_user(
...
-//         error!("Unable to find order for the given nonce");
-//         return Err(Default::default());
-//     }
-//     Ok(())
-// }
+//static CREATE_ORDER_NONCE: AtomicPtr<()> = AtomicPtr::new(0 as *mut ());
+//static CREATE_ORDER_CACHE: AtomicPtr<()> = AtomicPtr::new(0 as *mut ());
+//static CANCEL_ORDER_CACHE: AtomicPtr<()> = AtomicPtr::new(0 as *mut ());
+
+pub fn initialize_polkadex_gateway() {
```
Comment (haerdib) [inline enclave/src/polkadex_gateway.rs:444]: This will need some clean up.

File: enclave/src/polkadex_orderbook_storage.rs [hunk 15]
```diff
@@ -2,10 +2,9 @@ use crate::ed25519;
 use crate::polkadex_gateway::GatewayError;
```
Comment (haerdib) [inline enclave/src/polkadex_orderbook_storage.rs:2]: warning removals only..

File: enclave/src/polkadex_gateway.rs [hunk 16]
```diff
@@ -186,24 +253,56 @@ fn send_cancel_request_to_openfinex(order_uuid: &OrderUUID) -> Result<(), Gatewa
...
     let cancelled_order = polkadex_orderbook_storage::lock_storage_and_remove_order(&order_uuid)?;
     match (cancelled_order.order_type, cancelled_order.side) {
         (OrderType::LIMIT, OrderSide::BID) => {
             let price = cancelled_order
                 .price
                 .ok_or(GatewayError::LimitOrderPriceNotFound)?;
+
+            // TODO: Why are we converting the amounts here? The OpenFinex API is responsible for doing all the conversions?
+            // Even if we had to convert, we should not do a floating point conversion
             let amount =
```
Comment (Gauthamastro) [inline enclave/src/polkadex_gateway.rs:303]: yes, we shouldn't use the float here, we can change it to substrate-fixed

Comment (Gauthamastro) [reply enclave/src/polkadex_gateway.rs:303]: @mullefel I think you are working on the fixed point numbers once your PR is merged we can change this one

File: enclave/src/polkadex_gateway.rs (hunk 13 above)
Comment (Gauthamastro) [reply enclave/src/polkadex_gateway.rs:279]: Commented part is not required unless @ksr30 has some ideas for it, @ksr30 please share your thoughts since you coded that part

**Review by Gauthamastro — APPROVED** [review]
I have looked at the trading part and a general overview of the remaining codebase. I don't have enough knowledge to evaluate the SGX WS client part. 

LGTM
