### PR TITLE
Fix broken untrusted CLI calls in client

### LINKED ISSUE #82: Client CLI: Untrusted calls require --mrenclave when getting keystore path
When running untrusted calls from the client, certain commands fail saying they require the `--mrenclave` parameter. This is because we're calling into `get_keystore_path` which seems to need this. This could be a bug introduced when refactoring these helper functions for #2 

See on develop: https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/5d2a040e39a4b8f7e1d7cea9b430734bf9fa23d8/stf/src/cli_utils/account_parsing.rs#L70-L73 

The issue seems, that in that refactoring the keystore getter is now shared, even though the untrusted side has its own keystore (and way of getting the path to it), see code from master branch (before refactoring): https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/abd6bf25d0b653639ca141f838d5ebb151adec61/client/src/main.rs#L142

### PR DESCRIPTION
**Pull request by murerfel**
Fix untrusted calls in client that tried to use trusted keystore instead of untrusted one

This was introduced in a previous refactoring, as part of
https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/30

Resolves #82

### CODE REVIEW

File: stf/src/cli_utils/account_parsing.rs [hunk 1]
```diff
@@ -27,7 +27,8 @@ use sp_runtime::traits::IdentifyAccount;
 use std::path::PathBuf;
 use substrate_client_keystore::LocalKeystore;
 
-const KEYSTORE_PATH: &str = "my_trusted_keystore";
+const TRUSTED_KEYSTORE_PATH: &str = "my_trusted_keystore";
+const UNTRUSTED_KEYSTORE_PATH: &str = "my_keystore";
```
Comment (murerfel) [inline stf/src/cli_utils/account_parsing.rs:31]: name the trusted and untrusted keystores explicitly

File: stf/src/cli_utils/account_parsing.rs [hunk 2]
```diff
@@ -43,16 +44,29 @@ pub fn get_accountid_from_str(account: &str) -> AccountId {
...
+pub fn get_pair_from_str_untrusted(account: &str) -> sr25519::AppPair {
+    let keystore_path = get_untrusted_keystore_path();
+    get_pair_from_str(keystore_path, account)
+}
+
+/// get a pair either form keyring (well known keys) or from the TRUSTED keystore
+pub fn get_pair_from_str_trusted(matches: &ArgMatches<'_>, account: &str) -> sr25519::AppPair {
+    let keystore_path = get_trusted_keystore_path(matches);
+    get_pair_from_str(keystore_path, account)
+}
```
Comment (murerfel) [inline stf/src/cli_utils/account_parsing.rs:57]: We have a `get_pair_from_str` method for both the trusted and untrusted side. The only difference is the underlying keystore they're using

File: stf/src/cli_utils/account_parsing.rs [hunk 3]
```diff
@@ -43,16 +44,29 @@ pub fn get_accountid_from_str(account: &str) -> AccountId {
...
+                "fetching from keystore at {}",
+                keystore_path.as_path().display().to_string()
+            );
             // open store without password protection
-            let store =
-                LocalKeystore::open(get_keystore_path(matches), None).expect("store should exist");
+            let store = LocalKeystore::open(keystore_path, None).expect("store should exist");
             info!("store opened");
             let _pair = store
                 .key_pair::<sr25519::AppPair>(
```
Comment (murerfel) [inline stf/src/cli_utils/account_parsing.rs:72]: This code can still be shared across trusted and untrusted version

File: client/src/main.rs [hunk 4]
```diff
@@ -121,7 +121,7 @@ fn main() {
             Command::new("new-account")
                 .description("generates a new account for the substraTEE chain")
                 .runner(|_args: &str, matches: &ArgMatches<'_>| {
-                    let store = LocalKeystore::open(get_keystore_path(matches), None).unwrap();
+                    let store = LocalKeystore::open(get_untrusted_keystore_path(), None).unwrap();
```
Comment (murerfel) [inline client/src/main.rs:126]: Get the untrusted keystore everywhere in `client/src/main`

File: stf/src/cli.rs [hunk 5]
```diff
@@ -87,7 +87,8 @@ pub fn cmd(perform_operation: OperationRunner) -> MultiCommand<str, str> {
             Command::new("new-account")
                 .description("generates a new incognito account for the given substraTEE shard")
                 .runner(|_args: &str, matches: &ArgMatches<'_>| {
-                    let store = LocalKeystore::open(get_keystore_path(matches), None).unwrap();
+                    let store =
+                        LocalKeystore::open(get_trusted_keystore_path(matches), None).unwrap();
```
Comment (murerfel) [inline stf/src/cli.rs:91]: Get the trusted keystore everywhere in `stf/src/cli.rs`

File: stf/src/cli_utils/account_parsing.rs (hunk 2 above)
Comment (brenzi) [reply stf/src/cli_utils/account_parsing.rs:57]: we should someday get rid of this redundancy I think

**Review by brenzi — CHANGES_REQUESTED** [review]
I believe something is fundamentally misplaced here.

there should be a strict separation between all

untrusted calls
* which *never* involve the subcommand `trusted`
* which *always* use the untrusted keystore
* which are *all* coded in `/client/`
* only talk to the chain

trusted calls
* which *always* involve the subcommand `trusted`
* which *always* use the trusted keystore
* which are *all* coded in `/stf/src/cli.rs`
* only talk to the worker, either directly through worker RPC or indirectly through chain

I only looked at this code briefly, but it really looks wrong to me because there is a mixup of trusted and untrusted. Is there a good reason why we stopped separating these calls strictly?

**Comment by brenzi** [comment]
I believe I was wrong. In the case of PDEX we need to supply the beneficiary owner and proxy signature (which are in untrusted keystore) to the rpc api.
So, probably we shouldn't have a `trusted` keystore at all, but rather use the same for onchain and gateway

The intention of the `trusted` subcommand was to clearly separate confidential offchain stuff (where we have the same function calls, but targeted at offchain stf, like `transfer`) from publicly visible onchain stuff. In our case, this distinction  may not be neccessary.

Anyway, this can be left for later refactoring. I approve this PR

**Review by brenzi — APPROVED** [review]

**Comment by murerfel** [comment]
The reason for the refactoring were the new RPC calls and their respective CLI commands for Polkadex. I saw there was a lot of duplicated code, but failed to understand there was this clear distinction between `trusted` and `untrusted` calls. So we ended up with less duplicated code, but all the commands used the trusted keystore. This should be rectified by this PR.

However, this also means that the untrusted commands use some functions that are in `/stf/*`. Either we have some common place to share these functions (maybe `/stf/*` is not the right place?) or we accept that we duplicate quite a bit of code, which is problematic imho.

For Polkadex we have both, trusted and untrusted calls. What Bigna did in https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/86 are all on the untrusted side. The RPC calls (`place_order`, `cancel_order`, `withdraw`, `get_balance`) are on the trusted side. Is that correct @brenzi ?

**Comment by brenzi** [comment]
well, for PolkaDEX, *trusted* could probably be dropped. We should only distinguish direct and indirect calls, which doesn't exactly map to trusted / untrusted

**Comment by brenzi** [comment]
but for the PoC, don't worry too much. We just need to file a refactoring issue

**Comment by murerfel** [comment]
I opened an issue for this improvement, @brenzi : https://github.com/Polkadex-Substrate/polkadexTEE-worker/issues/90
